### ISSUE TITLE
Could not find CIFs

### ISSUE THREAD

**Issue by olibclarke** [YoshitakaMo/localcolabfold#80] opened 2022-04-27 18:21 UTC
Hi, when I try to run Colabfold_batch on a test case as follows:

`~/software/colabfold_batch/bin/colabfold_batch --amber --templates --num-recycle 8 --model-type AlphaFold2-multimer-v2 pfcrt_colabfold_input.csv pfcrt_tmp/`

I get the attached error. Am I doing something wrong, or how do I get around this issue?

```
If you require more MSAs, please host your own API and pass it to `--host-url`
2022-04-27 14:14:45,998 Running colabfold 1.3.0 (d6b0670552ce3f39e20b69f9e01521ca39562336)
2022-04-27 14:14:46,000 Found 8 citations for tools or databases
2022-04-27 14:14:49,729 Query 1/1: Complex (length 894)
2022-04-27 14:14:49,754 Could not find CIFs in pfcrt_tmp/Complex_env/templates_101
2022-04-27 14:14:49,754 Could not get MSA/templates for Complex: Could not find CIFs in pfcrt_tmp/Complex_env/templates_101
Traceback (most recent call last):
  File "/usr/local/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1140, in run
    host_url,
  File "/usr/local/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 637, in get_msa_and_templates
    query_seqs_unique[index],
  File "/usr/local/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 113, in mk_template
    obsolete_pdbs_path=None,
  File "/usr/local/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/data/templates.py", line 828, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in pfcrt_tmp/Complex_env/templates_101
2022-04-27 14:14:49,755 Done```

**Comment by YoshitakaMo** [comment] 2022-06-05 03:10
This issue may be caused by ColabFold project at that time. Now it should be fixed. Please update and try it again.

**Closed** 2022-08-24 01:25 UTC
