### ISSUE TITLE
Command-line version of AF2-Multimer?

### ISSUE THREAD

**Issue by gundalav** [YoshitakaMo/localcolabfold#34] opened 2021-11-08 12:28 UTC
Hi Yoshitaka-san, 

As you mentioned [AF2-Multimer ](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb)seem to be available now.
Is there a way we can port it to command line version? 
Just like your great [AF2_advanced](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb#scrollTo=ITcPnLkLuDDE). 

G.V.

**Comment by YoshitakaMo** [comment] 2021-11-09 03:32
AF2-Multimer runs on command-line interface. How about installing it from DeepMind repository? It's very nice!

**Comment by xvazquezc** [comment] 2021-11-09 23:44
The folks from Colabfold are already working on incorporating it into their code to work with MMSeqs2
https://twitter.com/thesteinegger/status/1455768659717095427
It should be quite straightforward to include it here once they release it.

**Comment by YoshitakaMo** [comment] 2021-11-10 01:17
Yes, I notice it, and the colabfold team including me is now testing the new version in the background. The new Google Colab notebook will be released in a few days. I'll also port it into this repository.

**Comment by YoshitakaMo** [comment] 2021-11-11 09:39
The new notebook compatible with AF2-Multimer is now public. I'll port it into this repository, but please wait for a few days until I'm free.

Alternatively, Colabfold now has a `colabfold_batch` command to run it locally. Read more about it here: https://github.com/sokrypton/ColabFold#running-locally

**Comment by gitgyj** [comment] 2021-11-14 23:28
Thanks for the work, I am wondering whether the upcoming AF2-Multimer code that is compatible with local machine would be using Jackhmmer?

**Comment by ShannonTown** [comment] 2021-11-19 04:14
> Alternatively, Colabfold now has a `colabfold_batch` command to run it locally. Read more about it here: https://github.com/sokrypton/ColabFold#running-locally

Hi, I was wondering if `colabfold_batch` can run a fasta file with complexes (multiple sequences)? I tried and it only returned the structure for the first sequence.

**Comment by konstin** [comment] 2021-11-19 04:48
@ShannonTown Yes, since yesterday actually: https://github.com/sokrypton/ColabFold/pull/88 (for older versions, you can use the csv input)

**Comment by ShannonTown** [comment] 2021-11-19 07:14
Thank you. I replaced the batch.py file in my virtual environment, "`Python3Env/lib/python3.7/site-packages/colabfold/batch.py`", and ran `colabfold_batch` again, but still got the same result. Is there anything else I need to do to update it? (I'm new to linux and all of these, appreciate your help!)

If I were to try csv input, how should I make the csv files? I couldn't find an example.

**Comment by konstin** [comment] 2021-11-19 09:53
I recommend `pip uninstall -y colabfold && pip install git+github.com/sokrypton/ColabFold` over manually changing files. For the input format, you need to put the whole complex in one line with colons (`:`) between the chains

**Comment by ShannonTown** [comment] 2021-11-19 19:23
Hi, I reinstalled colabfold and put the whole complex in one line with colons between chains, and got the following error:

`If you require more MSAs, please host your own API and pass it to `--host-url`
2021-11-19 14:21:07,419 Found 5 citations for tools or databases
2021-11-19 14:21:15,490 Query 1/1: Hemoglobin (length 581)
2021-11-19 14:21:15,584 Could not predict Hemoglobin: Invalid character in the sequence: :
Traceback (most recent call last):
  File "/alpha/Python3Env/lib/python3.7/site-packages/colabfold/batch.py", line 624, in run
    sequence=sequence, description="none", num_res=len(sequence)
  File "/alpha/Python3Env/lib/python3.7/site-packages/alphafold/data/pipeline.py", line 43, in make_sequence_features
    map_unknown_to_x=True)
  File "/alpha/Python3Env/lib/python3.7/site-packages/alphafold/common/residue_constants.py", line 580, in sequence_to_onehot
    raise ValueError(f'Invalid character in the sequence: {aa_type}')
ValueError: Invalid character in the sequence: :
Traceback (most recent call last):
  File "/alpha/Python3Env/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/alpha/Python3Env/lib/python3.7/site-packages/colabfold/batch.py", line 862, in main
    recompile_all_models=args.recompile_all_models,
  File "/alpha/Python3Env/lib/python3.7/site-packages/colabfold/batch.py", line 648, in run
    np_example = features_for_chain[protein.PDB_CHAIN_IDS[0]]
KeyError: 'A'
`

Here's what I put in the fasta file:

>sp|P69905|HBA_HUMAN Hemoglobin subunit alpha OS=Homo sapiens OX=9606 GN=HBA1 PE=1 SV=2
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR:MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH:MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR:MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH

**Comment by ShannonTown** [comment] 2021-11-19 20:05
I put the 4 chains in a .csv file with 2 columns, one named "id", the other named "sequence", and colabfold_batch returned the following error:

Traceback (most recent call last):
  File "/alpha/Python3Env/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/alpha/Python3Env/lib/python3.7/site-packages/colabfold/batch.py", line 835, in main
    queries, is_complex = get_queries(args.input, args.sort_queries_by)
  File "/alpha/Python3Env/lib/python3.7/site-packages/colabfold/batch.py", line 319, in get_queries
    (seqs, header) = pipeline.parsers.parse_fasta(file.read_text())
  File "/alpha/Python3Env/lib/python3.7/site-packages/alphafold/data/parsers.py", line 89, in parse_fasta
    sequences[index] += line
IndexError: list index out of range


Thank you!

**Comment by CYP152N1** [comment] 2021-11-19 21:43
Did The .fasta file contain ">" at the beginning of  1st line?

https://zhanggroup.org/FASTA/

**Comment by ShannonTown** [comment] 2021-11-19 21:45
Yes, it contains a ">" at the first line, somehow the ">" was interpreted as a sign for quote

**Comment by CYP152N1** [comment] 2021-11-19 21:47
Certainly. I got it.

**Comment by hz424** [comment] 2021-11-22 19:22
@ShannonTown I ran into the same issue/error you had. Have you figured out a way to fix this? Thanks!!

**Comment by ShannonTown** [comment] 2021-11-23 18:32
@hz424 I managed to modify the [AlphaFold2_mmseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) notebook to run locally in Jupyter, and it worked for multimers when I put colons between chains. 

Still not sure why in the command line `colabfold_batch` doesn't work. may it it has something to do with how the queries are imported.

**Comment by konstin** [comment] 2021-11-24 03:26
@ShannonTown Could it be your case is also https://github.com/sokrypton/ColabFold/issues/97#issuecomment-976746512?

For running it locally, what modification did you have to make, and did see you the [local runtimes option in colab](https://research.google.com/colaboratory/local-runtimes.html)?

**Comment by ShannonTown** [comment] 2021-11-24 06:16
@konstin 
> 
> For running it locally, what modification did you have to make, and did see you the [local runtimes option in colab](https://research.google.com/colaboratory/local-runtimes.html)?

I think I didn't use the local runtime options in colab because I was not aware of this before. I included my local virtual environment as sys.path, which has colabfold installed, and ran the program locally. 
pkgdir = '/xxxxxxxx/lib/python3.7/site-packages/'
sys.path.insert(0, pkgdir)



@hz424 I looked at [ sokrypton/ColabFold#97 (comment)](https://github.com/sokrypton/ColabFold/issues/97#issue-1060541341) and batch.py, I think the problem is that function `def get_queries` only takes fasta files when the input path is a directory, as instructed by the README:
        'colabfold_batch <directory_with_fasta_files> <result_dir> '

If we use the file path as input, I think it will work with a fasta file if you put colon between chains (seems that it will not work if you use '<_fasta name_' to separate different sequences.):
        `colabfold_batch /xxxxxxxxx/xxxxx.fasta <result_dir> `
or   `colabfold_batch /xxxxxxxxx/xxxxx.csv <result_dir> `

I think right now the batch mode only works for a directory of fasta files each with a single chain, but doesn't work for a directory of fasta files each with multiple chains.


PS, @konstin , in line 181-187, the 'def predict_structure' function put the start time after the prediction step, so every time the output prediction time is 0.0 sec.

**Comment by andzajan** [comment] 2021-12-10 14:56
Hi @ShannonTown, I know discussion is quite old now, but the proper format for `csv` import should be like this. `batch.py` data import function is looking for column names `id` and `sequence`.

Fasta file or multiple fasta files in the same folder won't work with `--model-type AlphaFold2-multimer`.

```
id,sequence
Complex,VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR:MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH:MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR:MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH
```

**Closed** 2022-02-05 05:32 UTC

**Comment by jenchem** [comment] 2022-08-04 16:51
> Hi @ShannonTown, I know discussion is quite old now, but the proper format for `csv` import should be like this. `batch.py` data import function is looking for column names `id` and `sequence`.
> 
> Fasta file or multiple fasta files in the same folder won't work with `--model-type AlphaFold2-multimer`.
> 
> ```
> id,sequence
> Complex,VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR:MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH:MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR:MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH
> ```

So for AF multiuser v2 I need to create a sequence file named 1abc.csv with the following in this format:

id,sequence
Complex,QWERTY : ASDFGH

**Comment by ShannonTown** [comment] 2022-08-04 18:03
Thanks so much for your reply! I got it after using it for some time.
