### ISSUE TITLE
No GPU/TPU found

### ISSUE THREAD

**Issue by canfeng-HUA** [YoshitakaMo/localcolabfold#17] opened 2021-10-05 09:14 UTC
Thanks a lot for providing this excellent tool for us. However, I met a problem about No GPU/TPU found. Could you please help me to fix it?

After I run 
`colabfold-conda/bin/python3.7 runner.py TF_CPP_MIN_LOG_LEVEL=0 `
It returns:

> ColabFold on Mac
> homooligomer: '1'
> total_length: '59'
> working_directory: 'prediction_test_a5e17'
> running mmseqs2
>   0%|          | 0/5 [elapsed: 00:00 remaining: ?]
> WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
> Traceback (most recent call last):
>   File "runner.py", line 596, in <module>
>     cf.clear_mem("gpu")
>   File "/Users/huacanfeng/Documents/AF2/colabfold/colabfold.py", line 55, in clear_mem
>     backend = jax.lib.xla_bridge.get_backend(device)
>   File "/Users/huacanfeng/Documents/AF2/colabfold/colabfold-conda/lib/python3.7/site-packages/jax/lib/xla_bridge.py", line 234, in get_backend
>     raise RuntimeError(f"Unknown backend {platform}")
> RuntimeError: Unknown backend GPU

The information for my MacBook Pro
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 16 GB 2400 MHz DDR4
Graphics: Intel UHD Graphics 630 1536 MB

**Comment by YoshitakaMo** [comment] 2021-10-06 02:10
Sorry for the inconvenience. The issue occurs on Mac. Now I fixed it. Please download `runner.py` again on the colabfold directory, 
`wget https://raw.githubusercontent.com/YoshitakaMo/localcolabfold/main/runner.py -O runner.py`
then restart the prediction. If the problem is resolved, please close this issue.

**Closed** 2021-10-06 10:34 UTC
